<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cwa/cwa.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CrowdNotifierData</code>
 */
class CrowdNotifierData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bytes publicKey = 2;</code>
     */
    protected $publicKey = '';
    /**
     * Generated from protobuf field <code>bytes cryptographicSeed = 3;</code>
     */
    protected $cryptographicSeed = '';
    /**
     * exact semantic tbd
     *
     * Generated from protobuf field <code>uint32 type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $publicKey
     *     @type string $cryptographicSeed
     *     @type int $type
     *           exact semantic tbd
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cwa\Cwa::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes publicKey = 2;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->publicKey;
    }

    /**
     * Generated from protobuf field <code>bytes publicKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->publicKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes cryptographicSeed = 3;</code>
     * @return string
     */
    public function getCryptographicSeed()
    {
        return $this->cryptographicSeed;
    }

    /**
     * Generated from protobuf field <code>bytes cryptographicSeed = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCryptographicSeed($var)
    {
        GPBUtil::checkString($var, False);
        $this->cryptographicSeed = $var;

        return $this;
    }

    /**
     * exact semantic tbd
     *
     * Generated from protobuf field <code>uint32 type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * exact semantic tbd
     *
     * Generated from protobuf field <code>uint32 type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

}

